version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: 'us-east-1'
    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACOUNT_ID }}
    IMAGE_REPO_NAME: ${{ secrets.IMAGE_REPO_NAME }}

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t telegraf .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
